### ISSUE TITLE
Infernal Robotics is not distributed with it's parts

### ISSUE THREAD

**Issue by labo-css** [KSP-CKAN/CKAN-meta#1103]
http://forum.kerbalspaceprogram.com/index.php?/topic/104535-10511-pre-magic-smoke-industries-infernal-robotics-0214200-beta/&page=34#comment-2515686

>  Important notice!
> 
> Legacy Parts are now a separate download. Core of the mod is distributed partless.
> 
> This is a beta version for a pre-release version 1.1 of KSP, so there WILL be bugs. Please report bugs and ask questions in this thread.
> 
>  
> 
> Download (release):  https://github.com/MagicSmokeIndustries/InfernalRobotics/releases/tag/2.0.0
> 
> Legacy Parts download: https://github.com/MagicSmokeIndustries/InfernalRobotics/releases/download/2.0.0-beta/IR-LegacyParts.zip 

The package distributed on CKAN contain no parts.

**Comment by plague006** [comment]
Thanks for the heads up. https://github.com/KSP-CKAN/NetKAN/pull/3774

**Comment by labo-css** [comment]
Hello, i don't understand how CKAN/Netkan works, it seems you did things on the netkan repo with that issue but this is not (yet) on ckan. I see regulary a netkan bot making commits and i don't know how all of this works, can you help me a little to understand why using the netkan repo instead of the ckan repo and what all of this involved?

**Comment by politas** [comment]
The pull request hadn't been merged, yet. Now it has, so InfernalRobotics-LegacyParts should now appear.

**Comment by plague006** [comment]
Ah thanks for hitting this @politas I saw it yesterday but didn't have time to reply adequately.

So NetKAN is a repository of metadata that points to sites we can scrape information from (such as new releases, mod compatibility, etc.). By contrast CKAN-meta is a repository of metadata that is complete. CKAN-meta is what the CKAN client downloads for users since it contains all versions of mods whereas NetKAN contains only 1 file per mod which we inflate with new information for every release.
