### ISSUE TITLE
Final Frontier ribbon packs

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN-meta#1104]
Oh no! We tried to overwrite a file owned by another mod!

If this problem re-occurs, then it maybe a packaging bug.
Please including the following information in your report:

File           : GameData/STMRibbons/EngRoles/FinalFrontierCustomRibbons.cfg
Installing Mod : STMsFFRibbonPackExpeditionRibbons 0.5.1
Owning Mod     : STMsFFRibbonPackEngineeringRoles
CKAN Version   : v1.16.1-0-g2e91715 (beta)

**Comment by plague006** [comment]
I believe this was an author packaging mistake. Version 0.5.1 seems to have included all the STM Ribbon packs inside it while Version 5.1.1 only the relevant folder is included. The changelog also states `Fixed download contents and minor rewording.`.

5.1.1 has been the current version since https://github.com/KSP-CKAN/CKAN-meta/commit/db72cb7968a0d212c253954750c59b86cf7e4a90 8 days ago. Hitting refresh in the CKAN client should clear this issue up. If it doesn't feel free to re-open.
