### ISSUE TITLE
TMSTACLSRetexture not listed

### ISSUE THREAD

**Issue by tambo1** [KSP-CKAN/CKAN-meta#1114]
Hi there,

I've noticed that since the spacedock transfer, my mod isn't being served up by the CKAN application.

The netkan file seems to be generated correctly...

https://github.com/KSP-CKAN/CKAN-meta/commits/0c4cf3db5f5cce992b338301efdd5396b08d2d84/TMSTACLSRetexture/TMSTACLSRetexture-2.2.1.ckan

...but doesn't get listed.

This was the case for 1.1 and now 1.1.1 (presumably will be for 1.1.2, which has just been announced).

Any advice you can give about where I/we are going wrong?

**Comment by plague006** [comment]
While this is present in the CKAN index the client doesn't surface the mod because it's impossible to install. We *should* allow users to see mods that can't be installed and it's in the queue of issues.

CKAN can't install `TMSTACLSRetexture` because the dependency on `TACLS` can't be met (no release since `v0.11.2` for KSP `1.0.5`.

**Comment by tambo1** [comment]
Ah, fair enough.  Makes sense.

Thanks for taking the time to answer.

**Comment by plague006** [comment]
No problem.
