### ISSUE TITLE
Enviromental Visual Enhancements Installation

### ISSUE THREAD

**Issue by heartstroke** [KSP-CKAN/CKAN-meta#266]
File           : GameData/EnvironmentalVisualEnhancements/Plugins/CityLights.dll
Installing Mod : EnvironmentalVisualEnhancements-Config-Default 7-4
Owning Mod     : EnvironmentalVisualEnhancements
CKAN Version   : v1.5.6-0-g0000000 (beta)

**Comment by SpaceTeph** [comment]
It should be fixed by now. There are three mods with EVE:

EnvironmentalVisualEnhancements (base mod)
EnvironmentalVisualEnhancements-HR (high-res config)
EnvironmentalVisualEnhancements-LR (low-res config)

EnvironmentalVisualEnhancements-Config-Default was wrong and has been removed. Try updating the repository data, uninstalling everything EVE-related, then installing EVE and EVE-HR or -LR, then tell me how it went :smile:

**Comment by heartstroke** [comment]
I just unchecked the config and installed the planetshine config instead
(bc I use planetshine) which worked perfectly.

2015-01-22 12:10 GMT+01:00 Teph <notifications@github.com>:

**Comment by Ippo343** [comment]
In this case, I'm closing this issue.
In the future, please open support tickets at KSP-CKAN/CKAN-support :)
