### ISSUE TITLE
Automatic install of NoMoreGrind/KCT configs for RP-0?

### ISSUE THREAD

**Issue by aw1621107** [KSP-CKAN/CKAN-meta#292]
Is it possible for CKAN to automatically install the NoMoreGrind/KCT config files present in the RP-0 download? I see in the registry file there's a section to describe what goes where, but I'm not sure if certain technical limitations prevent these configs from being applied, especially since they're not full mods...

**Comment by Ippo343** [comment]
The only issue would be if KCT's settings need to be overwritten. If KCT ships with a default settings file, then RP-0 cannot overwrite it and the installation will throw an error.

We can still work around that though using config packages like we are doing for RemoteTech.

**Comment by aw94** [comment]
Ah, that makes sense. Would this be the right place to request such a thing, or should I go to the forums?

**Comment by Ippo343** [comment]
No, github is definitely our preferred channel. I'll see to it as soon as I have the time.
In the meantime, if you'd like to help out you can take a look at how remote tech is doing it and try to do the same :)

**Comment by aw94** [comment]
All right, thanks! I'll see what I can do. I'm not very familiar with the github pull request model, though, so I may have to pop back for some questions later...

**Comment by aw94** [comment]
Alright, took a look at how RemoteTech works, as well as the files already present in No More Grind/KCT...

KCT seems to use the same strategy that RemoteTech does (generate default configs if none found), so I think I can make a config file for that. I'll try tomorrow, once I get some sleep.

No More Grind, though, provides its own config file, so (as I found out the hard way) CKAN won't copy the RP-0 config even if I delete the default one manually (I think). In this case, would I have to submit a pull request to the No More Grind author to do something more like KCT/RemoteTech? I could easily be missing something though since I'm not very familiar with CKAN...

**Comment by aw94** [comment]
Oh, also, what should I put for author/license/version numbers?

**Comment by Ippo343** [comment]
Well, I guess in this case NoMoreGrind has a conflict with RP-0. We should mark them as incompatible in the metadata, I believe.

As for the author, license, etc, I say you should just copy the ones from RP-0 (since the file still comes from the same download). Thanks for helping us out! :)

**Comment by aw94** [comment]
So tried a pull request, not sure if that's the right way to go about this?

How would marking RP-0/No More Grind as incompatible work, though, since it seems those two are updated automatically? Would I need to make the changes over at the NetKAN repo?

**Comment by AlexanderDzhoganov** [comment]
Sorry I haven't seen this earlier, I'm the author of No More Grind. I think a much better approach would be to incorporate the source into RP-0 as it's really 50ish lines of code. Here is [the whole source](https://gist.github.com/AlexanderDzhoganov/ba1185a66406e9c646f5), which I now release in the public domain so you can use it however.

**Comment by pjf** [comment]
Gosh dang it, I'm on both the CKAN and RP-0 projects. And yes, we definitely want CKAN to install the KCT and NMG files.

Given that NMG *is* so small, I've no problems compiling it directly into RP-0 as @AlexanderDzhoganov  suggests. Alternatively, rather than having NMG read a config file directly, we can tweak it to read from ConfigNodes, which means not having to worry about overwriting files (we can use ModuleManager stanzas to do config), although that does change existing behaviour. We can also do both, which feels like the best solution (we compile NMG into RP-0, but tweak it to read from ConfigNodes). cc'ing in @NathanKell , although I'm happy to do the work here.

KCT seems to only create config files if they don't already exist, so @aw94's metadata should work, although it'd be great to:

- [ ] Have the KCT RP-0 config be a netkan file that triggers off RP-0 releases.
- [ ] Have RP-0 metadata suggest or recommend the KCT config.

~ pjf

**Comment by aw94** [comment]
I'll see if I can figure out the netkan file for KCT.

**Comment by NathanKell** [comment]
That sounds good to me. I won't be doing coding until I get home though, so if you'd rather not wait a week do please go ahead and do that. I'm happy to help via IRC though. :)

**Comment by aw94** [comment]
Alright, @pjf, KCT stuff seems to be done.

**Comment by Dazpoet** [comment]
I'm going to throw out a wild guess at this being done in our parts so I'm closing this in hopes of being correct. If not poke it open again :)
