### ISSUE TITLE
Modify dependencies for Interstellar 0.90

### ISSUE THREAD

**Issue by crimsonseth** [KSP-CKAN/CKAN-meta#318]
KSPInterstellar-0.13.6.ckan refers as dependencies :
- CommunityResourcePack
- ModuleManager
- Toolbar
- TreeLoader
- TweakScale

(and installs WarpPlugin and ORSResourcePack)

whereas the actual zip (with dependencies) contains :
- CommunityResourcePack
- ModuleManager
- Toolbar
- OpenResourceSystem
- ORSResourcePack
- TechManager
- WarpPlugin

also KSPI 0.13.6 comes with a fix for TweakScale.
(http://forum.kerbalspaceprogram.com/threads/104943-0-90-KSP-Interstellar-port-maintance-thread)

**Comment by Dazpoet** [comment]
Looking at the .ckan file it would appear TreeLoader is used rather than TechManager, from what I gather they appear to have similar functionalities? @hakan42 is marked as maintainer of the file and might be able to shed some light on as to why that is the case.

The tweakscale fix requires overwriting of files, something that CKAN does not support and therefor it cannot be added to CKAN.

**Comment by Dazpoet** [comment]
Techmanager is now used rather than treeloader. The installation of KSPI through CKAN will install ORSResourcePack but not ORS itself, I'm unsure if this has an effect or not on the mod.

**Comment by Dazpoet** [comment]
In accordance with http://forum.kerbalspaceprogram.com/threads/104943-0-90-KSP-Interstellar-port-maintance-thread KSPI depends on CRP rather than ORS as of version 13.4 and as such I'll close this issue as resolved =)
