### ISSUE TITLE
adding request: Engine Ignitor

### ISSUE THREAD

**Issue by abenkovskii** [KSP-CKAN/CKAN-meta#337]
https://kerbalstuff.com/mod/84/Engine_Ignitor
There is already a repack of this mod for RealFuels in the database. However it requires [depends on] RF while original mod does not.

**Comment by Dazpoet** [comment]
Interesting problem. Looking at the zip that's being downloaded by the unofficial repack it shouldn't depend on but merely recommend RealFuels since I don't see anything RealFuels specific. Based on the [forumthread](http://forum.kerbalspaceprogram.com/threads/51880) it should probably also recommend KAS and RasterPropMonitor.

I'll make a PR and ping the modmaintainer with it.
