### ISSUE TITLE
request: Infernal Robotics - Model Rework

### ISSUE THREAD

**Issue by abenkovskii** [KSP-CKAN/CKAN-meta#350]

**Comment by Dazpoet** [comment]
These are now available on Kerbalstuff which has kindly reminded us to fix them into CKAN through https://github.com/KSP-CKAN/NetKAN/pull/905

This is not a CKAN-meta issue but a NetKAN one and since a PR now exists to remind us I will close this issue.

PS: I love the Model Rework aswell so it's sure to get added once I have the time
