### ISSUE TITLE
ToadicusTools is not updating via NetKAN

### ISSUE THREAD

**Issue by toadicus** [KSP-CKAN/CKAN-meta#410]
ToadicusTools has three versions on KerbalStuff that do not appear in the CKAN despite a NetKAN file suggesting that they should.  Two version (7, 8) may be corrupted, but version 9 is not.  Is this a CKAN/NetKAN problem, or are corrupted archives at any point in the version history intentionally blocking?

TIA

**Comment by Dazpoet** [comment]
It seems our indexing bot is currently taking a nap, awaiting a dev who can give it a whack to wake up (darn timezones).

Your version 8a installs fine on my local tests so once the bot jumps into action it should be indexed. Acctually since I _really_ want tweakable everything working again I'm in the process of manually adding ToadicusTools to our current index right now. Will be up shortly.
