### ISSUE TITLE
SCANsat update

### ISSUE THREAD

**Issue by DMagic1** [KSP-CKAN/CKAN-meta#563]
Do I need to do anything to get SCANsat updated? I released 12.1 on Kerbal Stuff on Saturday. Does it have to do with the screwy versioning, v12.1 vs 12.1?

**Comment by Dazpoet** [comment]
We're having some kind of trouble, waiting for the right people to look into it. See https://github.com/KSP-CKAN/NetKAN-bot/issues/13

**Comment by Dazpoet** [comment]
The bot is up an running again and I've set a x_netkan_force_v to account for the version being different than before, if newer versions have a v again the argument will become dormant since it checks if a v already exists. Closing this since it would appear the issue has been resolved. Poke it again if you think I've missed something :)
