### ISSUE TITLE
License confusion on Airlock

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/CKAN-meta#762]
Airlock's metadata says it is MIT, but the mod's description says only "CC-NC-ND". Presumably it's meant to be under that CC license and have a description which is slightly more informative. (I suggest "Airlock adds a small cost in ElectricCharge (and Oxygen, with a suitable life support mod) each time a kerbal goes on EVA.")

**Comment by plague006** [comment]
Basically, the author changed some things around between the time the mod was added to KerbalStuff and the time it was added to CKAN.

I double checked the history to make sure I didn't goof it up and when KerbalStuff's bot send us the info, the license was definitely MIT (https://github.com/KSP-CKAN/NetKAN/pull/1950/files).

The author also changed how the mod is packaged which is why 1.0.1 wasn't automatically indexed. Version 1.0.1 of the mod will be added and the abstract for 1.0 will be corrected. Not 100% sure on what'll happen with the license.

Thanks for bringing this to my attention.
