### ISSUE TITLE
DeepFreeze blocks REPOSoftTech-Agencies 

### ISSUE THREAD

**Issue by valuial** [KSP-CKAN/CKAN-meta#766]
Installing previously uninstalled mod REPOSoftTech-Agencies

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/REPOSoftTech/Agencies/Agents.cfg
Installing Mod : REPOSoftTech-Agencies V1.0.2.0
Owning Mod     : DeepFreeze
CKAN Version   : v1.14.0-0-g4242285 (beta)

Your GameData has been returned to its original state.

Error!

---

ckan update does not fix this.
(DeepFreeze needs to depend on REPOSoftTech-Agencies and not use it's own copy thereof.)

**Comment by plague006** [comment]
This is occuring because of https://github.com/KSP-CKAN/NetKAN/pull/2221 which came about when the author re-did the distribution of his agencies. 

To resolve this you'll have to uninstall `DeepFreeze` and then you should be able to install `DeepFreeze` and its dependency `REPOSoftTech-Agencies`. Please let me know whether this resolves the situation or not.

**Comment by valuial** [comment]
DeepFreeze still needs --no-recommends or pull in multiple LifeSupport mods. But with the option when reinstalling it solves the problem. Thanks.
